"""20 post/storie Instagram — Crypto Italia Facile (ITA + ENG)."""

from __future__ import annotations

HOME_LINK = "https://satoshiallien.github.io/cryptoitaliafacile/index.html"

# topic keys map to image_style.TOPICS + brand_overlay icons
BATCH_20: list[dict] = [
    # 1–5 Bitcoin & Blockchain
    {
        "id": 1,
        "slug": "batch-btc-21-milioni",
        "category": "bitcoin_blockchain",
        "category_it": "Bitcoin & Blockchain",
        "category_en": "Bitcoin & Blockchain",
        "topic": "bitcoin",
        "hook_it": "Solo 21 milioni\ndi Bitcoin ₿",
        "hook_en": "Only 21 million\nBitcoin ever ₿",
        "body_it": "La scarsità è il cuore di Bitcoin. Nessuno può stamparne altri — capire questo cambia tutto.",
        "body_en": "Scarcity is the heart of Bitcoin. No one can print more — understanding this changes everything.",
        "desc_it": "Guida semplice su offerta fissa, halving e perché BTC è diverso dalle valute tradizionali.",
        "desc_en": "Simple guide on fixed supply, halving and why BTC differs from fiat money.",
        "cta_it": "Scopri Bitcoin su Crypto Italia Facile",
        "cta_en": "Learn Bitcoin on Crypto Italia Facile",
        "graphic_minimal": "Sfondo nero, titolo bianco, icona ₿ arancione Satoshi (#F59E0B), badge BITCOIN",
        "graphic_advanced": "Gradient navy, card centrale, barra arancione top, logo brand, QR link in basso",
        "sticker_position": "Sticker LINK: centro-basso, 120px sopra safe zone (y≈1520)",
    },
    {
        "id": 2,
        "slug": "batch-btc-blockchain-spiegato",
        "category": "bitcoin_blockchain",
        "category_it": "Bitcoin & Blockchain",
        "category_en": "Bitcoin & Blockchain",
        "topic": "bitcoin",
        "hook_it": "Blockchain in\n60 secondi ⛓️",
        "hook_en": "Blockchain in\n60 seconds ⛓️",
        "body_it": "Un registro condiviso, immutabile e verificabile da tutti. Niente banca al centro.",
        "body_en": "A shared, immutable ledger verified by everyone. No bank in the middle.",
        "desc_it": "Spiegazione zero-gergo per chi inizia: blocchi, nodi e consenso.",
        "desc_en": "Zero-jargon explanation for beginners: blocks, nodes and consensus.",
        "cta_it": "Impara su Crypto Italia Facile",
        "cta_en": "Learn on Crypto Italia Facile",
        "graphic_minimal": "Nero/bianco, catena di blocchi stilizzata, accento arancione",
        "graphic_advanced": "Icone digitali blocchi collegati, glow arancione, layout premium",
        "sticker_position": "Sticker LINK: angolo basso destro, sopra CTA button",
    },
    {
        "id": 3,
        "slug": "batch-btc-lightning-sats",
        "category": "bitcoin_blockchain",
        "category_it": "Bitcoin & Blockchain",
        "category_en": "Bitcoin & Blockchain",
        "topic": "bitcoin",
        "hook_it": "Lightning:\npaga in sats ⚡",
        "hook_en": "Lightning:\npay in sats ⚡",
        "body_it": "Micro-pagamenti Bitcoin veloci e a basso costo. I sats sono frazioni di BTC.",
        "body_en": "Fast, low-cost Bitcoin micropayments. Sats are fractions of BTC.",
        "desc_it": "Cos'è Lightning Network e perché serve per l'uso quotidiano di Bitcoin.",
        "desc_en": "What Lightning Network is and why it matters for everyday Bitcoin use.",
        "cta_it": "Guida Lightning — link sotto",
        "cta_en": "Lightning guide — link below",
        "graphic_minimal": "Fulmine arancione su nero, testo bianco, badge LIGHTNING",
        "graphic_advanced": "Wallet + fulmine, gradient teal/orange, footer con URL",
        "sticker_position": "Sticker LINK: centro, sotto card principale (y≈920)",
    },
    {
        "id": 4,
        "slug": "batch-btc-halving-cicli",
        "category": "bitcoin_blockchain",
        "category_it": "Bitcoin & Blockchain",
        "category_en": "Bitcoin & Blockchain",
        "topic": "bitcoin",
        "hook_it": "Halving:\ncosa cambia 📉",
        "hook_en": "Halving:\nwhat changes 📉",
        "body_it": "Ogni ~4 anni la ricompensa ai miner si dimezza. Meno nuovi BTC sul mercato.",
        "body_en": "Every ~4 years miner rewards halve. Fewer new BTC hit the market.",
        "desc_it": "Cicli, storia e cosa osservare senza hype né previsioni di prezzo.",
        "desc_en": "Cycles, history and what to watch — without hype or price predictions.",
        "cta_it": "Analisi educativa su Crypto Italia Facile",
        "cta_en": "Educational analysis on Crypto Italia Facile",
        "graphic_minimal": "Grafico minimal arancione, anno halving, sfondo scuro",
        "graphic_advanced": "Timeline halving, icone miner, stile fintech premium",
        "sticker_position": "Sticker LINK: basso-centro, allineato al pulsante CTA",
    },
    {
        "id": 5,
        "slug": "batch-btc-self-custody",
        "category": "bitcoin_blockchain",
        "category_it": "Bitcoin & Blockchain",
        "category_en": "Bitcoin & Blockchain",
        "topic": "wallet",
        "hook_it": "Not your keys\nnot your coins 🔑",
        "hook_en": "Not your keys\nnot your coins 🔑",
        "body_it": "Self-custody significa controllare tu le chiavi. È libertà, ma anche responsabilità.",
        "body_en": "Self-custody means you control the keys. Freedom — and responsibility.",
        "desc_it": "Differenza tra exchange e wallet personale, spiegata in modo semplice.",
        "desc_en": "Exchange vs personal wallet — explained simply.",
        "cta_it": "Wallet sicuri — Crypto Italia Facile",
        "cta_en": "Secure wallets — Crypto Italia Facile",
        "graphic_minimal": "Chiave + lucchetto arancione, nero, testo bianco",
        "graphic_advanced": "Hardware wallet icon, card viola/navy, CTA arancione",
        "sticker_position": "Sticker LINK: sinistra basso, sopra URL testuale",
    },
    # 6–10 Crypto Education
    {
        "id": 6,
        "slug": "batch-edu-primi-passi",
        "category": "crypto_education",
        "category_it": "Crypto Education",
        "category_en": "Crypto Education",
        "topic": "guide",
        "hook_it": "Primi passi\ncrypto 🎓",
        "hook_en": "First steps\nin crypto 🎓",
        "body_it": "Exchange, wallet, verifica identità: ordine corretto per iniziare senza errori.",
        "body_en": "Exchange, wallet, KYC: the right order to start without mistakes.",
        "desc_it": "Percorso principianti passo dopo passo — zero tecnicismi.",
        "desc_en": "Step-by-step beginner path — zero jargon.",
        "cta_it": "Inizia da qui — Crypto Italia Facile",
        "cta_en": "Start here — Crypto Italia Facile",
        "graphic_minimal": "Badge GUIDA, libro icon, arancione su nero",
        "graphic_advanced": "Checklist 1-2-3, layout educativo premium",
        "sticker_position": "Sticker LINK: centro-basso (y≈1480)",
    },
    {
        "id": 7,
        "slug": "batch-edu-exchange-sicuro",
        "category": "crypto_education",
        "category_it": "Crypto Education",
        "category_en": "Crypto Education",
        "topic": "exchange",
        "hook_it": "Scegli l'exchange\ngiusto 💱",
        "hook_en": "Pick the right\nexchange 💱",
        "body_it": "Regolamentazione, 2FA, reputazione e fee: cosa controllare prima di registrarti.",
        "body_en": "Regulation, 2FA, reputation and fees: what to check before signing up.",
        "desc_it": "Checklist exchange sicuro per utenti italiani.",
        "desc_en": "Secure exchange checklist for Italian users.",
        "cta_it": "Confronta exchange su Crypto Italia Facile",
        "cta_en": "Compare exchanges on Crypto Italia Facile",
        "graphic_minimal": "Icone exchange, teal accent, CTA arancione",
        "graphic_advanced": "Tabella fee/regolazione stilizzata, fintech dark",
        "sticker_position": "Sticker LINK: destra, sopra footer @krown.82",
    },
    {
        "id": 8,
        "slug": "batch-edu-gas-fee",
        "category": "crypto_education",
        "category_it": "Crypto Education",
        "category_en": "Crypto Education",
        "topic": "ethereum",
        "hook_it": "Gas fee:\ncosa sono ⛽",
        "hook_en": "Gas fees:\nwhat they are ⛽",
        "body_it": "Ogni transazione on-chain costa. Impara a leggere gas, gwei e network.",
        "body_en": "Every on-chain tx costs. Learn gas, gwei and networks.",
        "desc_it": "Ethereum e L2 spiegati senza confusione.",
        "desc_en": "Ethereum and L2 explained without confusion.",
        "cta_it": "Guida gas — Crypto Italia Facile",
        "cta_en": "Gas guide — Crypto Italia Facile",
        "graphic_minimal": "Pompa gas stilizzata, viola/indaco, testo bianco",
        "graphic_advanced": "Grafico fee + badge ETH, layout premium",
        "sticker_position": "Sticker LINK: basso, tra CTA e URL",
    },
    {
        "id": 9,
        "slug": "batch-edu-dca-strategia",
        "category": "crypto_education",
        "category_it": "Crypto Education",
        "category_en": "Crypto Education",
        "topic": "tip",
        "hook_it": "DCA: compra\ncon calma 📊",
        "hook_en": "DCA: buy\nsteadily 📊",
        "body_it": "Dollar Cost Averaging riduce lo stress del timing. Piccole somme, costanza.",
        "body_en": "Dollar Cost Averaging reduces timing stress. Small amounts, consistency.",
        "desc_it": "Strategia educativa — non consiglio finanziario.",
        "desc_en": "Educational strategy — not financial advice.",
        "cta_it": "Approfondisci su Crypto Italia Facile",
        "cta_en": "Learn more on Crypto Italia Facile",
        "graphic_minimal": "Grafico DCA lineare, arancione, minimal",
        "graphic_advanced": "Calendario acquisti + icona grafico, stile tip",
        "sticker_position": "Sticker LINK: centro-basso sopra safe zone",
    },
    {
        "id": 10,
        "slug": "batch-edu-defi-base",
        "category": "crypto_education",
        "category_it": "Crypto Education",
        "category_en": "Crypto Education",
        "topic": "defi",
        "hook_it": "DeFi spiegato\nfacile 🌊",
        "hook_en": "DeFi made\nsimple 🌊",
        "body_it": "Finanza decentralizzata: prestiti, swap e yield — rischi inclusi.",
        "body_en": "Decentralised finance: lending, swaps and yield — risks included.",
        "desc_it": "Concetti base prima di toccare qualsiasi protocollo.",
        "desc_en": "Core concepts before touching any protocol.",
        "cta_it": "DeFi per principianti — Crypto Italia Facile",
        "cta_en": "DeFi for beginners — Crypto Italia Facile",
        "graphic_minimal": "Onde DeFi verdi su nero, badge DeFi",
        "graphic_advanced": "Protocolli stilizzati, warning box rosso, CTA arancione",
        "sticker_position": "Sticker LINK: angolo basso sinistro",
    },
    # 11–15 Sicurezza & Antifrode
    {
        "id": 11,
        "slug": "batch-sec-seed-phrase",
        "category": "sicurezza_antifrode",
        "category_it": "Sicurezza & Antifrode",
        "category_en": "Security & Anti-fraud",
        "topic": "sicurezza",
        "hook_it": "MAI condividere\nla seed phrase 🚨",
        "hook_en": "NEVER share\nyour seed phrase 🚨",
        "body_it": "12-24 parole = accesso totale al wallet. Nessun supporto ufficiale le chiederà mai.",
        "body_en": "12-24 words = full wallet access. No real support will ever ask for them.",
        "desc_it": "Regola #1 della sicurezza crypto. Salvala offline.",
        "desc_en": "Crypto security rule #1. Store offline.",
        "cta_it": "Checklist sicurezza — Crypto Italia Facile",
        "cta_en": "Security checklist — Crypto Italia Facile",
        "graphic_minimal": "Rosso warning, lucchetto, seed barrata",
        "graphic_advanced": "Shield + seed phrase blur, badge SICUREZZA",
        "sticker_position": "Sticker LINK: centro, sotto alert box",
    },
    {
        "id": 12,
        "slug": "batch-sec-phishing",
        "category": "sicurezza_antifrode",
        "category_it": "Sicurezza & Antifrode",
        "category_en": "Security & Anti-fraud",
        "topic": "sicurezza",
        "hook_it": "Phishing\ncrypto 🎣",
        "hook_en": "Crypto\nphishing 🎣",
        "body_it": "Email, DM e siti clone: controlla sempre l'URL prima di inserire dati.",
        "body_en": "Emails, DMs and clone sites: always verify the URL before entering data.",
        "desc_it": "Come riconoscere truffe comuni nel 2026.",
        "desc_en": "How to spot common scams in 2026.",
        "cta_it": "Proteggiti — Crypto Italia Facile",
        "cta_en": "Protect yourself — Crypto Italia Facile",
        "graphic_minimal": "Amo phishing rosso, URL fake barrato",
        "graphic_advanced": "Browser bar + warning, antifrode layout",
        "sticker_position": "Sticker LINK: basso-destra",
    },
    {
        "id": 13,
        "slug": "batch-sec-2fa",
        "category": "sicurezza_antifrode",
        "category_it": "Sicurezza & Antifrode",
        "category_en": "Security & Anti-fraud",
        "topic": "sicurezza",
        "hook_it": "2FA sempre\nattivo 🔐",
        "hook_en": "Always enable\n2FA 🔐",
        "body_it": "Authenticator app > SMS. Proteggi exchange e email con doppio fattore.",
        "body_en": "Authenticator app > SMS. Protect exchanges and email with 2FA.",
        "desc_it": "Setup 2FA in 3 minuti — guida pratica.",
        "desc_en": "Set up 2FA in 3 minutes — practical guide.",
        "cta_it": "Guida 2FA — Crypto Italia Facile",
        "cta_en": "2FA guide — Crypto Italia Facile",
        "graphic_minimal": "Icona 2FA, numeri OTP, arancione",
        "graphic_advanced": "Phone + authenticator mockup, premium security",
        "sticker_position": "Sticker LINK: centro-basso",
    },
    {
        "id": 14,
        "slug": "batch-sec-hardware-wallet",
        "category": "sicurezza_antifrode",
        "category_it": "Sicurezza & Antifrode",
        "category_en": "Security & Anti-fraud",
        "topic": "wallet",
        "hook_it": "Hardware wallet\nper somme serie 🛡️",
        "hook_en": "Hardware wallet\nfor serious amounts 🛡️",
        "body_it": "Chiavi offline su dispositivo dedicato. La scelta per self-custody seria.",
        "body_en": "Offline keys on a dedicated device. The choice for serious self-custody.",
        "desc_it": "Ledger, Trezor e best practice — confronto educativo.",
        "desc_en": "Ledger, Trezor and best practices — educational comparison.",
        "cta_it": "Wallet sicuri — Crypto Italia Facile",
        "cta_en": "Secure wallets — Crypto Italia Facile",
        "graphic_minimal": "Device USB stilizzato, chiave offline",
        "graphic_advanced": "Hardware wallet hero, cold storage badge",
        "sticker_position": "Sticker LINK: sopra URL, y≈1580",
    },
    {
        "id": 15,
        "slug": "batch-sec-antifrode-ps",
        "category": "sicurezza_antifrode",
        "category_it": "Sicurezza & Antifrode",
        "category_en": "Security & Anti-fraud",
        "topic": "sicurezza",
        "hook_it": "Antifrode:\n8 anni PayPal 🛡️",
        "hook_en": "Anti-fraud:\n8 years at PayPal 🛡️",
        "body_it": "Pattern fraudolenti, account ad alto rischio e mitigazione perdite — esperienza reale.",
        "body_en": "Fraud patterns, high-risk accounts and loss mitigation — real experience.",
        "desc_it": "Sicurezza crypto con mentalità antifrode professionale.",
        "desc_en": "Crypto security with a professional fraud-prevention mindset.",
        "cta_it": "Sicurezza crypto — Crypto Italia Facile",
        "cta_en": "Crypto security — Crypto Italia Facile",
        "graphic_minimal": "Shield PayPal-style, badge ANTIFRODE",
        "graphic_advanced": "Risk dashboard mockup, fintech premium",
        "sticker_position": "Sticker LINK: basso-centro",
    },
    # 16–20 News & Trend
    {
        "id": 16,
        "slug": "batch-news-btc-oggi",
        "category": "news_trend",
        "category_it": "News & Trend",
        "category_en": "News & Trend",
        "topic": "breaking",
        "hook_it": "Bitcoin news\ndel momento 📡",
        "hook_en": "Bitcoin news\nright now 📡",
        "body_it": "Aggiornamenti BTC senza hype: macro, regolazione e adozione istituzionale.",
        "body_en": "BTC updates without hype: macro, regulation and institutional adoption.",
        "desc_it": "News curate da Crypto Italia Facile — fonti verificate.",
        "desc_en": "Curated news from Crypto Italia Facile — verified sources.",
        "cta_it": "Leggi le news — Crypto Italia Facile",
        "cta_en": "Read the news — Crypto Italia Facile",
        "graphic_minimal": "Badge BREAKING rosso, ticker BTC",
        "graphic_advanced": "News ticker animation style, radar icon",
        "sticker_position": "Sticker LINK: centro-basso",
    },
    {
        "id": 17,
        "slug": "batch-news-mica-eu",
        "category": "news_trend",
        "category_it": "News & Trend",
        "category_en": "News & Trend",
        "topic": "regulation",
        "hook_it": "MiCA EU:\ncosa cambia ⚖️",
        "hook_en": "EU MiCA:\nwhat changes ⚖️",
        "body_it": "Nuovo quadro regolatorio europeo per crypto. Cosa significa per chi opera in EU.",
        "body_en": "New European crypto regulatory framework. What it means for EU users.",
        "desc_it": "Trend 2026 spiegato in linguaggio accessibile.",
        "desc_en": "2026 trend explained in plain language.",
        "cta_it": "Trend MiCA — Crypto Italia Facile",
        "cta_en": "MiCA trend — Crypto Italia Facile",
        "graphic_minimal": "Bandiera EU + bilancia, giallo accent",
        "graphic_advanced": "Regulation document mockup, premium news",
        "sticker_position": "Sticker LINK: basso, sopra footer",
    },
    {
        "id": 18,
        "slug": "batch-news-etf-flussi",
        "category": "news_trend",
        "category_it": "News & Trend",
        "category_en": "News & Trend",
        "topic": "trend",
        "hook_it": "ETF Bitcoin:\nflussi istituzionali 📈",
        "hook_en": "Bitcoin ETFs:\ninstitutional flows 📈",
        "body_it": "Capire flussi in entrata/uscita senza seguire il rumore di mercato.",
        "body_en": "Understand inflows/outflows without market noise.",
        "desc_it": "Macro trend per chi vuole contesto, non trading tips.",
        "desc_en": "Macro trend for context — not trading tips.",
        "cta_it": "Analisi trend — Crypto Italia Facile",
        "cta_en": "Trend analysis — Crypto Italia Facile",
        "graphic_minimal": "Grafico freccia su, badge TREND 2026",
        "graphic_advanced": "ETF flow chart stylized, gold accent",
        "sticker_position": "Sticker LINK: destra basso",
    },
    {
        "id": 19,
        "slug": "batch-news-cardano-midnight",
        "category": "news_trend",
        "category_it": "News & Trend",
        "category_en": "News & Trend",
        "topic": "cardano",
        "hook_it": "Cardano &\nMidnight 🔷",
        "hook_en": "Cardano &\nMidnight 🔷",
        "body_it": "Ecosistema ADA in evoluzione: smart contract, governance e privacy layer.",
        "body_en": "Evolving ADA ecosystem: smart contracts, governance and privacy layer.",
        "desc_it": "Focus Cardano senza tribalismo — solo fatti.",
        "desc_en": "Cardano focus without tribalism — facts only.",
        "cta_it": "Sezione Cardano — Crypto Italia Facile",
        "cta_en": "Cardano section — Crypto Italia Facile",
        "graphic_minimal": "Logo ADA blu, badge CARDANO",
        "graphic_advanced": "Midnight privacy theme, dual chain visual",
        "sticker_position": "Sticker LINK: centro-basso",
    },
    {
        "id": 20,
        "slug": "batch-news-satoshi-ai",
        "category": "news_trend",
        "category_it": "News & Trend",
        "category_en": "News & Trend",
        "topic": "tip",
        "hook_it": "Parla con\nSatoshi AI 🤖",
        "hook_en": "Talk to\nSatoshi AI 🤖",
        "body_it": "Assistente crypto in italiano: Bitcoin, sicurezza, DeFi — risposte chiare.",
        "body_en": "Italian crypto assistant: Bitcoin, security, DeFi — clear answers.",
        "desc_it": "Prova l'AI educativa su Crypto Italia Facile. Zero gergo.",
        "desc_en": "Try the educational AI on Crypto Italia Facile. Zero jargon.",
        "cta_it": "Chatta con Satoshi — Crypto Italia Facile",
        "cta_en": "Chat with Satoshi — Crypto Italia Facile",
        "graphic_minimal": "Bot icon arancione, chat bubble, CTA tap",
        "graphic_advanced": "Satoshi mascot + chat UI mockup, premium",
        "sticker_position": "Sticker LINK: basso-centro — sticker principale Satoshi AI",
    },
]


def validate_batch() -> None:
    assert len(BATCH_20) == 20, f"Expected 20 items, got {len(BATCH_20)}"
    ids = [x["id"] for x in BATCH_20]
    assert ids == list(range(1, 21)), f"Bad numbering: {ids}"
    for item in BATCH_20:
        assert item.get("slug")
        cap_it = build_caption_it(item)
        cap_en = build_caption_en(item)
        assert HOME_LINK in cap_it, f"Missing link IT in #{item['id']}"
        assert HOME_LINK in cap_en, f"Missing link EN in #{item['id']}"
        assert cap_it.count(HOME_LINK) >= 2
        assert cap_en.count(HOME_LINK) >= 2


def build_caption_it(item: dict) -> str:
    link = HOME_LINK
    return (
        f"🔥 {item['hook_it'].replace(chr(10), ' ')}\n\n"
        f"{item['body_it']}\n\n"
        f"📝 {item['desc_it']}\n\n"
        f"👉 {item['cta_it']}\n"
        f"🔗 {link}\n\n"
        f"🌐 Tutte le guide: {link}\n\n"
        f"#Bitcoin #Crypto #CryptoItaliaFacile #CryptoEducation #SicurezzaCrypto"
    )[:2200]


def build_caption_en(item: dict) -> str:
    link = HOME_LINK
    return (
        f"🔥 {item['hook_en'].replace(chr(10), ' ')}\n\n"
        f"{item['body_en']}\n\n"
        f"📝 {item['desc_en']}\n\n"
        f"👉 {item['cta_en']}\n"
        f"🔗 {link}\n\n"
        f"🌐 All guides: {link}\n\n"
        f"#Bitcoin #Crypto #CryptoItaliaFacile #CryptoEducation #CryptoSecurity"
    )[:2200]


if __name__ == "__main__":
    validate_batch()
    for item in BATCH_20:
        cap = build_caption_it(item)
        assert HOME_LINK in cap
        assert cap.count(HOME_LINK) >= 2
    print("OK: 20 contenuti validati, link presente in tutte le caption.")